spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

server:
  servlet.context-path: /api
  port: 5000
